apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oncall-service
  template:
    metadata:
      labels:
        app: oncall-service
    spec:
      containers:
        - name: oncall-service
          image: docker.io/library/oncall-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: oncall-secrets
            - configMapRef:
                name: oncall-config

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
