bind 0.0.0.0
protected-mode no

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000

appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite no

save 900 1
save 300 10
save 60 10000

maxmemory-policy allkeys-lru

loglevel notice
logfile ""
